SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '1a34ac381646821f' HASH '063942e81f9bbd22e259a88beb6260ba7328a4c9ff7ff9f117b6b05b9a673394' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."M_USER"(
    "USER_ID" VARCHAR(254) NOT NULL,
    "ENCRYPTED_PASSWORD" VARCHAR(100) NOT NULL,
    "USER_NAME" VARCHAR(60) NOT NULL,
    "USER_ROLE" VARCHAR(20) NOT NULL,
    "USER_CLASS" CHAR(4),
    "USER_STUDENT_NO" VARCHAR(2),
    "USER_DARKMODE" BOOLEAN NOT NULL,
    "USER_STATUS" INT DEFAULT 1,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "CREATED_USER_ID" VARCHAR(254) NOT NULL,
    "UPDATE_AT" TIMESTAMP,
    "UPDATE_USER_ID" VARCHAR(254),
    "PASSWORD_ERROR_COUNT" INT DEFAULT 0
);          
ALTER TABLE "PUBLIC"."M_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("USER_ID");  
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.M_USER;  
INSERT INTO "PUBLIC"."M_USER" VALUES
('t-ukeire@hcs.ac.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', STRINGDECODE('\u53d7\u5165\u5148\u751f'), 'ROLE_TEACHER', 'S3A3', '', TRUE, 1, TIMESTAMP '2019-05-02 12:48:35', 't-ukeire@hcs.ac.jp', TIMESTAMP '2020-11-24 13:44:39.876', 't-ukeire@hcs.ac.jp', 0),
('s-ukeire@hcs.ac.jp', '$2a$10$ZCHmqKLzAXq39kCc6BoBS.5M59sRkHNFWT4aSk.MM2QsRfWQFtqnK', STRINGDECODE('\u53d7\u5165\u5b66\u751f'), 'ROLE_STUDENT', 'S3A1', '01', FALSE, 1, TIMESTAMP '2020-11-24 13:44:53.327', 't-ukeire@hcs.ac.jp', TIMESTAMP '2020-11-24 13:44:53.327', 't-ukeire@hcs.ac.jp', 0);         
CREATE MEMORY TABLE "PUBLIC"."EXAMREPORT"(
    "EXAMREPORT_ID" VARCHAR(10) NOT NULL,
    "USER_ID" VARCHAR(254) NOT NULL,
    "DEPARTMENT" CHAR(1),
    "COMPANY_NAME_TOP" CHAR(3),
    "REPORT_DAY" TIMESTAMP,
    "RECRUITMENT_NUMBER" INT,
    "COMPANY_NAME" VARCHAR(50),
    "APPLICATION_ROUTE" VARCHAR(10),
    "EXAM_DATE_TIME" DATETIME,
    "EXAMINATION_LOCATION" VARCHAR(50),
    "CONTENS_TEST" VARCHAR(10),
    "REMARKS" VARCHAR(600),
    "EXAM_REPORT_STATUS" VARCHAR(10)
);   
ALTER TABLE "PUBLIC"."EXAMREPORT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("EXAMREPORT_ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXAMREPORT;              
CREATE MEMORY TABLE "PUBLIC"."APPLICATION_AND_REPORT"(
    "EXAMINATION_REPORT_ID" VARCHAR(10) NOT NULL,
    "USER_ID" VARCHAR(254) NOT NULL,
    "EXAMINATION_STATUS_ID" CHAR(100) NOT NULL,
    "ACTION_ID" CHAR(50) NOT NULL,
    "ACTION_PLACE" VARCHAR(50) NOT NULL,
    "ACTION_DAY" DATETIME NOT NULL,
    "ACTION_END_DAY" DATETIME,
    "COMPANY_NAME" VARCHAR(50) NOT NULL,
    "ACTION_STATUS_ID" CHAR(50),
    "ATTENDANCE_ID" VARCHAR(100),
    "ATTENDANCE_DAY" DATETIME,
    "ATTENDANCE_END_DAY" DATETIME,
    "LODGING_DAY_ID" VARCHAR(50),
    "INFORMATION" VARCHAR(300),
    "SCHEDULE" VARCHAR(300),
    "CONTENTS_REPORT" VARCHAR(300)
);              
ALTER TABLE "PUBLIC"."APPLICATION_AND_REPORT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("EXAMINATION_REPORT_ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APPLICATION_AND_REPORT;  
ALTER TABLE "PUBLIC"."M_USER" ADD CONSTRAINT "PUBLIC"."USER_ID" FOREIGN KEY("CREATED_USER_ID") REFERENCES "PUBLIC"."M_USER"("USER_ID") NOCHECK;               
